### ISSUE TITLE
outofmemory java when build

### ISSUE THREAD

**Issue by thanhdatpd** [thanhdatpd/android_device_meizu_bicot#29]
[ 37% 179/482] /bin/bash -c "(rm -f /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar ) && (rm -rf /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/anno ) && (mkdir -p /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/ ) && (mkdir -p /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/anno ) && (/home/thanhdatpd/lineage/out/soong/host/linux-x86/bin/zipsync -d /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/srcjars -l /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/srcjar-list -f \"*.java\"  /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/aapt2.srcjar ) && (if [ -s /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/java-source-list -o -s /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/srcjar-list ] ; then /home/thanhdatpd/lineage/out/soong/host/linux-x86/bin/soong_javac_wrapper  prebuilts/jdk/jdk9/linux-x86/bin/javac -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -encoding UTF-8   -bootclasspath /home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar  -classpath /home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-auto-value-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/org.apache.http.legacy_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-common_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/com.android.vcard_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-commons-io-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-dagger2-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-disklrucache-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-gifdecoder-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-glide-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-all-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-context-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-core-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-okhttp-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-protobuf-lite-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-stub-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-javax-annotation-api-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-javax-inject-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-libshortcutbadger-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-mime4j-core-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-mime4j-dom-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-error-prone-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-guava-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-glide-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-glide-annotation-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-zxing-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/jsr305_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/libbackup_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/legacy-test_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/libphonenumber_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/volley_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/org.lineageos.platform.internal_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/libprotobuf-java-lite_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-dynamic-animation_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-core-ui_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-design_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-transition_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-v13_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-v4_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-appcompat_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-cardview_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-recyclerview_intermediates/classes-header.jar  -d /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes -s /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/anno  -source 1.8 -target 1.8  -processorpath /home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-auto-value_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-javapoet_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-dagger2_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-dagger2-compiler_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-dagger2-producers_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-glide-annotation_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-glide-compiler_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-guava_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-javax-annotation-api_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-javax-inject_intermediates/classes.jar -processor com.google.auto.value.processor.AutoValueProcessor,dagger.internal.codegen.ComponentProcessor,com.bumptech.glide.annotation.compiler.GlideAnnotationProcessor \\@/home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/java-source-list \\@/home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/srcjar-list || ( rm -rf /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes ; exit 41 ) fi ) && (prebuilts/jdk/jdk9/linux-x86/bin/jar -cf /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar     @<(find /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes -type f | sort | build/soong/scripts/jar-args.sh /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes; echo \"-C /home/thanhdatpd/lineage/out/empty .\") )"
FAILED: /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar 
/bin/bash -c "(rm -f /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar ) && (rm -rf /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/anno ) && (mkdir -p /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/ ) && (mkdir -p /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/anno ) && (/home/thanhdatpd/lineage/out/soong/host/linux-x86/bin/zipsync -d /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/srcjars -l /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/srcjar-list -f \"*.java\"  /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/aapt2.srcjar ) && (if [ -s /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/java-source-list -o -s /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/srcjar-list ] ; then /home/thanhdatpd/lineage/out/soong/host/linux-x86/bin/soong_javac_wrapper  prebuilts/jdk/jdk9/linux-x86/bin/javac -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -encoding UTF-8   -bootclasspath /home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar  -classpath /home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-auto-value-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/org.apache.http.legacy_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-common_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/com.android.vcard_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-commons-io-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-dagger2-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-disklrucache-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-gifdecoder-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-glide-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-all-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-context-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-core-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-okhttp-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-protobuf-lite-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-grpc-stub-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-javax-annotation-api-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-javax-inject-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-libshortcutbadger-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-mime4j-core-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-mime4j-dom-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-error-prone-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-guava-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-glide-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-glide-annotation-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/dialer-zxing-target_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/jsr305_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/libbackup_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/legacy-test_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/libphonenumber_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/volley_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/org.lineageos.platform.internal_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/libprotobuf-java-lite_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-dynamic-animation_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-core-ui_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-design_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-transition_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-v13_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-v4_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-appcompat_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-cardview_intermediates/classes-header.jar:/home/thanhdatpd/lineage/out/target/common/obj/JAVA_LIBRARIES/android-support-v7-recyclerview_intermediates/classes-header.jar  -d /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes -s /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/anno  -source 1.8 -target 1.8  -processorpath /home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-auto-value_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-javapoet_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-dagger2_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-dagger2-compiler_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-dagger2-producers_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-glide-annotation_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-glide-compiler_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-guava_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-javax-annotation-api_intermediates/classes.jar:/home/thanhdatpd/lineage/out/host/common/obj/JAVA_LIBRARIES/dialer-javax-inject_intermediates/classes.jar -processor com.google.auto.value.processor.AutoValueProcessor,dagger.internal.codegen.ComponentProcessor,com.bumptech.glide.annotation.compiler.GlideAnnotationProcessor \\@/home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/java-source-list \\@/home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/srcjar-list || ( rm -rf /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes ; exit 41 ) fi ) && (prebuilts/jdk/jdk9/linux-x86/bin/jar -cf /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes-full-debug.jar     @<(find /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes -type f | sort | build/soong/scripts/jar-args.sh /home/thanhdatpd/lineage/out/target/common/obj/APPS/Dialer_intermediates/classes; echo \"-C /home/thanhdatpd/lineage/out/empty .\") )"
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

**Comment by thanhdatpd** [comment]
The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: Java heap space
	at jdk.compiler/com.sun.tools.javac.code.Scope$ScopeImpl.dupUnshared(Scope.java:377)
	at jdk.compiler/com.sun.tools.javac.comp.MemberEnter.initEnv(MemberEnter.java:414)
	at jdk.compiler/com.sun.tools.javac.comp.MemberEnter.getInitEnv(MemberEnter.java:443)
	at jdk.compiler/com.sun.tools.javac.comp.MemberEnter.visitVarDef(MemberEnter.java:289)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:950)
	at jdk.compiler/com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:161)
	at jdk.compiler/com.sun.tools.javac.comp.MemberEnter.memberEnter(MemberEnter.java:173)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$MembersPhase.finishClass(TypeEnter.java:947)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$MembersPhase.runPhase(TypeEnter.java:931)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.doCompleteEnvs(TypeEnter.java:270)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$MembersPhase.doCompleteEnvs(TypeEnter.java:866)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:245)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:254)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:254)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter$Phase.completeEnvs(TypeEnter.java:254)
	at jdk.compiler/com.sun.tools.javac.comp.TypeEnter.complete(TypeEnter.java:195)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:633)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1314)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.complete(Enter.java:577)
	at jdk.compiler/com.sun.tools.javac.comp.Enter.main(Enter.java:554)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.enterTrees(JavaCompiler.java:1052)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:923)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:302)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:162)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
ninja: build stopped: subcommand failed.
00:00:10 ninja failed with: exit status 1

**Comment by thanhdatpd** [comment]
add -J-Xms2G -J-Xmx15G  to command will work well but i dont know how to add it to process of mka build(make build)

**Comment by thanhdatpd** [comment]
happyyy, can fix bay this solution: 
add `-J-Xmx15G`, in to build/soong/java/config/config.go

i will add that file motified to folder patch_for_lineage_folder in this repo
