### ISSUE TITLE
error today 3-4-5-7/8/2019

### ISSUE THREAD

**Issue by thanhdatpd** [thanhdatpd/android_device_meizu_bicot#51]
01-11 08:18:54.246  1354  1354 W SystemServer: ***********************************************
01-11 08:18:54.248  1354  1354 E SystemServer: BOOT FAILURE making display ready
01-11 08:18:54.248  1354  1354 E SystemServer: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.wm.WindowManagerService.displayReady()' on a null object reference
01-11 08:18:54.248  1354  1354 E SystemServer: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:760)
01-11 08:18:54.248  1354  1354 E SystemServer: 	at com.android.server.SystemServer.run(SystemServer.java:368)
01-11 08:18:54.248  1354  1354 E SystemServer: 	at..............

Update: Fix, see update timeline 31/7/2019.

**Comment by thanhdatpd** [comment]
E wcnss_service: open /persist/WCNSS_qcom_wlan_nv.bin failed(Permission denied).

E wcnss_service: nvbin_sendfile failed.


update: just removed wcnss_service, i think cant use wifi or anymore but it need to continue, i will fix it soon,.

**Comment by thanhdatpd** [comment]
okey, error today is about FlashlightController. 
FlashlightController: java.lang.AssertionError: Supported FPS ranges cannot be null.
android.hardware.camera2.legacy.LegacyMetadataMapper.mapControlAe(LegacyMetadataMapper.java:411)
Log booting:
[g23.txt](https://github.com/thanhdatpd/android_device_meizu_bicot/files/3458232/g23.txt)

**Comment by thanhdatpd** [comment]
AndroidRuntime: java.lang.UnsatisfiedLinkError: Unable to create namespace for the classloader dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/javax.obex.jar", zip file "/system/app/Bluetooth/Bluetooth.apk"],nativeLibraryDirectories=[/system/app/Bluetooth/lib/arm, /system/app/Bluetooth/Bluetooth.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/lib, /vendor/lib]]]: android_init_namespaces failed: error initializing public namespace: a library with soname "lib-ims-rcscmjni.so" was not found in the default namespace

**Comment by thanhdatpd** [comment]
SchedPolicy: add_tid_to_cgroup failed; fd=-1
 W ActivityManager: Failed setting process group of 3082 to 0
W System.err: java.lang.IllegalArgumentException: Invalid argument: 3082
 W System.err: 	at android.os.Process.setProcessGroup(Native Method)

**Comment by thanhdatpd** [comment]
wcnss_service: CAL file not found

Fixed, wlan driver not loading, i dont know why, so i added driver when boot sucess tringger like this:
see commit 28cc6c75a930b200e38f4f8dba7649b5c0737733

insmod /system/lib/modules/wlan.ko

**Comment by thanhdatpd** [comment]
Problem now: Sound, video record, bluetooth,..
